import "../scss/partials/colors.scss";
export const ARCColorArray = [
    {
        alias: "arc-teal",
        name: "Teal",
        class: "teal",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Tarmac",
        class: "tarmac",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Altitude Gray",
        class: "lightgray",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Concourse",
        class: "concourse",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Flap3",
        class: "flap3",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Fuselage",
        class: "fuselage",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Nightshade",
        class: "nightshade",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Signal Orange",
        class: "signalorange",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Airfield",
        class: "airfield",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Flare",
        class: "flare",
        dark: false,
        light: true,
    },
    {
        alias: "yellow",
        name: "Beacon",
        class: "beacon",
        dark: false,
        light: true,
    },
    {
        alias: "red",
        name: "Now Boarding",
        class: "nowboarding",
        dark: false,
        light: true,
    },
    {
        alias: "white",
        name: "Clear Skies",
        class: "white",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Fog",
        class: "fog",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Overcast",
        class: "overcast",
        dark: false,
        light: true,
    },
    {
        alias: "",
        name: "Landing",
        class: "landing",
        dark: false,
        light: true,
    },
    {
        alias: "black",
        name: "Autopilot",
        class: "black",
        dark: false,
        light: true,
    },
    
]