import "../scss/partials/colors.scss";
export const ARCColorArray = [
    {
        alias: "arc-teal",
        name: "Teal",
        class: "teal",
        dark: false,
        gray: false,
        light: true,
        note: "One of the primary colors of ARC's selections, primarily used as backgrounds and accents",
    },
    {
        alias: "",
        name: "Tarmac",
        class: "tarmac",
        dark: false,
        gray: true,
        light: true,
        note: "One of the most used colors, primarily for backgrounds and text colors",
    },
    {
        alias: "",
        name: "Altitude Gray",
        class: "lightgray",
        dark: true,
        gray: false,
        light: false,
        note: "Primarily used as an accent color for backgrounds",
    },
    {
        alias: "",
        name: "Concourse",
        class: "concourse",
        dark: false,
        gray: false,
        light: true,
        note: "Primarily used as an accent/ rarely used on the site",
    },
    {
        alias: "",
        name: "Flap3",
        class: "flap3",
        dark: true,
        gray: false,
        light: false,
        note: "Primarily used as an accent/ rarely used on the site",
    },
    {
        alias: "",
        name: "Fuselage",
        class: "fuselage",
        dark: false,
        gray: false,
        light: true,
        note: "Primarily used as an accent/ rarely used on the site",
    },
    {
        alias: "",
        name: "Night Shade",
        class: "nightshade",
        dark: false,
        gray: true,
        light: true,
        note: "Primarily used as an accent/ rarely used on the site",
    },
    {
        alias: "",
        name: "Signal Orange",
        class: "signalorange",
        dark: true,
        gray: false,
        light: false,
        note: "Primarily used as an accent/ rarely used on the site",
    },
    {
        alias: "",
        name: "Airfield",
        class: "airfield",
        dark: true,
        gray: false,
        light: false,
        note: "Primarily used as an accent/ rarely used on the site",
    },
    {
        alias: "",
        name: "Flare",
        class: "flare",
        dark: false,
        gray: false,
        light: false,
        note: "Primarily used as an accent/ rarely used on the site",
    },
    {
        alias: "yellow",
        name: "Beacon",
        class: "beacon",
        dark: true,
        gray: false,
        light: false,
        note: "Primarily used as an accent/ rarely used on the site",
    },
    {
        alias: "red",
        name: "Now Boarding",
        class: "nowboarding",
        dark: false,
        gray: false,
        light: false,
        note: "Primarily used as an accent/ rarely used on the site",
    },
    {
        alias: "white",
        name: "Clear Skies",
        class: "white",
        dark: true,
        gray: false,
        light: false,
        note: "One of the most used colors, primarily for backgrounds and text colors",
    },
    {
        alias: "",
        name: "Fog",
        class: "fog",
        dark: true,
        gray: false,
        light: false,
        note: "Primarily used as an accent color; Mainly used for text options",
    },
    {
        alias: "",
        name: "Overcast",
        class: "overcast",
        dark: true,
        gray: false,
        light: false,
        note: "Primarily used as an accent color; Mainly used for text options",
    },
    {
        alias: "",
        name: "Landing",
        class: "landing",
        dark: false,
        gray: false,
        light: false,
        note: "Primarily used as an accent color; Mainly used for text options",
    },
    {
        alias: "black",
        name: "Autopilot",
        class: "black",
        dark: false,
        gray: true,
        light: true,
        note: "One of the most used colors, primarily for backgrounds and text colors",
    },
    
]